# Generated by Django 2.1.5 on 2019-12-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('pdf', models.FileField(upload_to='mahdi/')),
                ('cover', models.ImageField(upload_to='mahdi/img/')),
            ],
        ),
    ]
