# Generated by Django 2.1.5 on 2019-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('pictured', models.ImageField(upload_to='mahdi/img/learn/')),
            ],
        ),
    ]
